name: Metrics
permissions:
  contents: write
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0-23/8 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install PyYAML
      - name: Generate metrics
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN2 }}
        run: |
          python gen.py --user hsfzxjy --output-stats metrics.svg --output-activity activity.svg
      - name: Commit and push changes
        run: |
          # push to metrics-render branch
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B metrics-render
          git add metrics.svg activity.svg
          git commit -m "Update metrics"
          git push -f origin metrics-render
